### ISSUE TITLE
The folder contents are unavailable because of an unknown error

### ISSUE THREAD

**Issue by marcopallotta** [cryptomator/ios#327] opened 2023-10-19 17:42 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

I purchased a new iPhone (model 13) that exited out of the box with iOS 16. So, first, I upgraded it to iOS 17 and then I migrated all of my data from my old iPhone (it had always  iOS 17). The question is that, even if I can unlock my vault, the result is that it's not shown in file. The error is "the folder contents are unavailable because of an unknown error". No issue with my iPad (iPadOS 17) and macOS (macOS 12). If I try to create a new vault from iPhone this is correctly shown, as well as it is from macOS but not with iPadOS. 

### What software is involved?

last mobile version with iOS 17

### Volume Type

None

### Steps to Reproduce

1 open cryptomator
2 unlock vault
3 the error is displayed in file

### Expected Behavior

The vault should be showed in File.

### Actual Behavior

Vault is not mounted in file.

### Reproducibility

Always

**Comment by phil1995** [comment] 2023-10-28 13:43
I think the issue here is that we don't handle the re-authorization of the underlying cloud providers yet. And if you migrate from one device to another afaik this is needed. So, although it's not the best UX, you can workaround this by deleting the vault in the Cryptomator app on the device where it's not working and add it again.

Note: Please be sure that you not delete the vault from the cloud provider itself but just from the Cryptomator app in the overview and then tap on edit or swipe left on the vault, i.e. do not delete the folder where your vault is stored. Otherwise you are risking to loose all your data.

In the future you should simply see a message that you need to login again via Google Drive, Dropbox or whatever your underlying cloud providers are :)

**Comment by marcopallotta** [comment] 2023-10-28 15:09
I don’t know what you mean about “re-authorization”. In past I migrated from one iPhone to another without any issue about Cryptomator and existing vault. Vault that is always on iCloud (so iPhone already authorized on it else I couldn’t access the vault). As I explained I could unlock the vault even if the result is the one I reported.
About removing the vault and re-adding it in Cryptomator I already did this (it was the first thing I did to workaround the problem) but with no success.
Moreover, as said, if I create a new vault from iPhone my iPad (gen 6 but with ipados17)  cannot see it correctly (same message as this post). With macOS no problems.
This is a very frustrating situation. I need my data from iPhone and I cannot do this.
The last chance is to try to create the vault from iPad and see if iPhone can unlock it correctly.
The problem is that I cannot have free space in the cloud to do this so I have to delete the old vault, after having backuped them and then re-create it.

**Comment by marcopallotta** [comment] 2023-11-01 11:00
However I can confirm that creating a new vault from my iPad isn't a warkaround as the same error of the bug report is present if I try to unlock it from my iPhone.
So:
1) creating vault from macOS is ok with macOS and iPad but no with iPhone
2) creating vault from iPad is ok from iPad and macOS but no with iPhone
3) creating vault from iPhone is ok from iPhone and macOS but no with iPad.


Let me know if this isn't a frustrating situation.
The problem is evidently on the mobile version of cryptomator, version that isn't update since 7 month ago (before the release if the last apple operating system).

**Comment by marcopallotta** [comment] 2023-11-01 11:17
Another info: I created a new vault from macOS and now this vault cannot be opened (same reported error) neither with iPhone nor with iPad (whereas the "original" vault, created with macOS many years ago, can be opened with iPad).
So this is a random behavior. :-(

**Comment by phil1995** [comment] 2023-11-01 11:32
I agree with you that it's a super frustrating situation. 
Would you be so kind to provide us logs (with enabled debug mode) so we can better investigate your issue?

How to export the log files from the Cryptomator 2.0 iOS app is described in the [documentation](https://docs.cryptomator.org/en/latest/ios/settings/).

You can either post them here in the thread or email them to us at support@cryptomator.org. Please keep in mind that the logs can contain sensitive information like plaintext paths or filenames, etc.

**Comment by sonnmar** [comment] 2023-11-01 20:19
I had the same Problem on iPhone 13 Pro with iOS 17.1 and iPad Air (Gen. 5) with iPadOS 17.1 using iCloud. It occurs on old (before upgrade to iOS 17.1) and new (after upgrade to iOS 17.1) folders, but it's not every new created folder affected.

 I can see the contend of the folder in iOS and iPadOS if I manually sync the file "dirid.c9r" in the crypted directory. I found the path of the right folder with the function to search the encrypted file in the MacOS Version of Cryptomator.

**Comment by sonnmar** [comment] 2023-11-01 20:28
My last comment may match to Issue #324 and Issue #316 to.

**Comment by marcopallotta** [comment] 2023-11-02 11:16
@phil1995 I attach logs from cryptomator 2.0 IOS app as you requested (the logs come from a new vault that I created, from macOS, to avoid publishing possibile sensitive data as its behavior is the same of my "production" vault).

Txs.
[Logs.zip](https://github.com/cryptomator/ios/files/13238164/Logs.zip)

**Comment by phil1995** [comment] 2023-11-02 17:39
Thanks for the logs @marcopallotta 🙂 I see that the vault is located in the iCloud container of the "classic" / legacy Cryptomator app. Could you please try if it makes any difference for you if you create a vault under macOS in iCloud Drive in a different place, i.e. out side of the Cryptomator folder / container?

As @tobihagemann pointed out in a different issue the error code we get from Apple here has not much documentation but it might be related to some weird permissions with app containers in iCloud.

**Comment by miguelarios** [comment] 2023-11-03 03:06
I too have this problem however my problem is actually happening with sub folders. So my vault has folders and files at the root vault in iCloud. Then I visit one of those folders that has additional folders inside and I get this same error. I can attach the log file. 
[org.cryptomator.ios.fileprovider 2023-11-03--02-46-38-845.log](https://github.com/cryptomator/ios/files/13246397/org.cryptomator.ios.fileprovider.2023-11-03--02-46-38-845.log)

**Comment by marcopallotta** [comment] 2023-11-03 19:13
@phil1995 I think you could be right. In fact I moved the test vault outside Cryptomator directory, in Cloud, and now iPhone can mount it in file without issues! 
I will do this thing with my production vault too (it shouldn't change too much for me) and then I will post the result.

Thank you for your support.

**Comment by marcopallotta** [comment] 2023-11-05 20:44
@phil1995 I think I spoke too early. In fact in iPhone now I can read the test vault (moved to iCloud root directory) but not with iPad with last iPadOS release 
[org.cryptomator.ios.fileprovider 2023-11-05--18-29-43-003.log.zip](https://github.com/cryptomator/ios/files/13260749/org.cryptomator.ios.fileprovider.2023-11-05--18-29-43-003.log.zip)
(in attach the logs).
Moreover I tried to move my production vault too outside Cryptomator iCloud directory but iPhone still doesn't open it (same error that I posted). 
I think there is unfortunately something other. 


Thank you.

**Comment by marcopallotta** [comment] 2023-11-05 20:57
I tried to create a new vault from iPhone (last release as macOS has 12.x release so not the last) and into iCloud root directory. Ok with iPhone and macOS but not with iPad. I think this is the real test without variables like operating system versions that are not the last ones. If I create a new vault from IOS 17.x (in iCloud root directory so we haven't the question of cryptomator legacy directory position) at least iPadOS (17.x) should read it.

**Comment by marcopallotta** [comment] 2023-11-11 07:53
In short: is there anybody that can create a new vault from IOS17 (last release) and can unlock it without issues in iPadOS 17 (last release) and viceversa? I haven't macOS14 so I cannot test this OS but at least from iPadOS to iOS and viceversa all should be run ok.

Because in my tests now this isn't possibile so it should be classified as a "great" bug.

**Comment by sonnmar** [comment] 2023-11-11 10:02
I made a new vault on my iPhone (iOS 17.1.1) directly in the iCloud-Folder and safe a file in it. I can unlock the vault, but I don't get the directory on my iPad (iPadOS 17.1.1). On my Mac (macOS 14.1.1) I can read the file. Vice versa I made a new vault on my iPad directly in the iCloud-Folder and safe a file in it. I cant' access the file from my iPhone but from my Mac. Before I test the reading I switched on the logging, but the logfiles are empty.
As I mentioned to an other issue, if I sync the file "deride.c9r" in the vaults-folder on iCloud manually by tapping on the cloud-symbols in file-app, I get access to the directory and can read the file. These works on both devices.

**Comment by marcopallotta** [comment] 2023-11-11 10:20
@sonnmar so you had confirmed the bug. I need to open the vault from both macOS, iOS and iPadOS (when I am outside my home) and now this is not possibile anymore (the strange thing is that I could do without problems with my old iPhone but always with latest release). The question about the sync of deride.c9r is not applicable in my situation as when I am outside my home I cannot identified the correct file to open as they have the uncrypted name.

**Comment by sonnmar** [comment] 2023-11-11 10:34
@marcopallotta I'm thinking it's a bug. But it is maybe a syncing-problem and not I migration-problem or a problem with access rights. And I had made a typo, the filename is "dirid.c9r".

**Comment by marcopallotta** [comment] 2023-11-11 11:52
@sonnmar the question is that I cannot explain to myself why in the "old" iPhone (XR) all worked ok whereas In the new one (13), but both with the same release (before I switched the phones the old one was fully updated), we have the issue.
Cryptomator release is always the same (as it hasn't been updated to new release for months).

You said that you have the same issue with iPhone 13 Pro: did the problem appear after the switch to new smartphone or after OS upgrade? In my situation (as said) after the switch (and same os release) so I can also suppose that starting from old software releases (either cryptomator or iOS), and upgrading them to the last (as happened to me in these last years) the problem, for reasons that I don't know, doesn't appear (situation that changes after you start "installing" last software releases).

**Comment by sonnmar** [comment] 2023-11-11 12:09
@marcopallotta I can not remember if the Problem occurs on my old iPhone, I update to 13 Pro from a 6s nearby 2 years ago. Actually it  bothers me since a few weeks. I use always an actual release of cryptomator an all my devices.

**Comment by ivanRylach** [comment] 2023-11-26 12:48
Seeing the same issue on iOS 17.1.1, Mac OS 14.1.1 with iCloud Sync.

Files app fails to display the content of sub-directories. When adding new files into the root of a vault - everything works great. It all started around iOS 16 to 17 upgrade.

Tried following approaches to address the issue:
- remove vault from iOS and import it again,
- create a brand new vault from Mac OS
- attempted above steps for Legacy types of vaults (a dedicated `Cryptomator` directory in iCloud) as well as new vaults created in the root of iCloud.

@tobihagemann @phil1995, I'm happy to help debugging this issue further

**Comment by andreagrandi** [comment] 2023-12-18 10:06
> Another info: I created a new vault from macOS and now this vault cannot be opened (same reported error) neither with iPhone nor with iPad (whereas the "original" vault, created with macOS many years ago, can be opened with iPad).
> 
> So this is a random behavior. :-(

I just had this exact issue. Note: I usually use Cryptomator on MacOS and iOS with a volume I keep on pCloud and I never had any issues. I wanted to give iCloud a try and this happened.

I created the volume on MacOS, then I picked my iPad and tried to open the volume. I got the error message saying the volume could not be opened because of an error.

I had an intuition and went on the File app visiting the encrypted folder (not the decrypted volume) and forcing the offline download of the files.

I went back to Cryptomator volume and now I was able to open it!

So in my case the issue was that Cryptomator wasn't able to automatically download the file it needed, but once I manually downloaded them, it was able to open the volume.

I'm not sure if this will be true for all the new folders and files, but it could be possible that at least the root folder (the one containing the Cryptomator master key) must be downloaded before it's able to open any other subfolders or files.

Ps: I'm using iOS 17.2 and MacOS 13.x

**Comment by marcopallotta** [comment] 2023-12-18 22:10
@andreagrandi thanks for your feedback. I checked in my iPhone and I realized that marsterkey.cryptomator and vault.cryptomator files (in vault root folder) are always just downloaded: obviously it's not true for the folder that contains all of my data and I'm afraid that downloading this folder could download all other subdirectories as well.....I should do some tests about this thing with a test vault to be sure.

**Comment by andreagrandi** [comment] 2023-12-19 09:29
> @andreagrandi thanks for your feedback. I checked in my iPhone and I realized that marsterkey.cryptomator and vault.cryptomator files (in vault root folder) are always just downloaded: obviously it's not true for the folder that contains all of my data and I'm afraid that downloading this folder could download all other subdirectories as well.....I should do some tests about this thing with a test vault to be sure.

The files in the root folder (only the files, not the folders) should be enough to make it work.

At least when I use it with pCloud, I don't have to sync down all the folders. Content is being downloaded the first time I try to access it, so I suppose it should be the same with iCloud storage.

**Comment by marcopallotta** [comment] 2023-12-20 16:28
@andreagrandi in my root cryptomator directory I only have mastery.cryptomator, vault.cryptomator (and their backup files) and a single folder that, inside, has other folders. So I cannot download this single directory.

**Comment by andreagrandi** [comment] 2023-12-20 17:23
> @andreagrandi in my root cryptomator directory I only have mastery.cryptomator, vault.cryptomator (and their backup files) and a single folder that, inside, has other folders. So I cannot download this single directory.

I never said you have to download the folder. I even wrote "only the files, not the folder "

**Comment by marcopallotta** [comment] 2023-12-20 18:04
@andreagrandi then I hadn’t understood what you suggested. You said that you should download only the files in root folder. I supposed Cryptomator root folder but if you mean only encrypted files related to the ones that I want to access then it’s not useful for mobile users as I can only discover this only in the desktop app.

**Comment by marcopallotta** [comment] 2024-01-20 17:49
Unfortunately same issues with last IOS mobile version too (I was looking forward for it for months)
I don't know ..... this is a very bad situation. I haven't be able to access my data outside my home for almost three months.
Maybe the only solution is to move data outside vault: at last we have to surrender.

**Comment by ivanRylach** [comment] 2024-01-21 20:34
I managed to resolve this issue on iOS 17 by forcing iCloud to download all the files for the directory, which holds the target vault. Steps:
1. In Files app, open up "iCloud Drive" directory and locate the directory, which holds the target vault,
2. Long press on that directory and select "Download Now",
3. Wait till download is finished, then open this vault using Cryptomator.

I hope it helps someone else.

**Comment by miguelarios** [comment] 2024-01-21 20:57
> I managed to resolve this issue on iOS 17 by forcing iCloud to download all the files for the directory, which holds the target vault. Steps:
> 
> 1. In Files app, open up "iCloud Drive" location and find the directory, which holds the target vault,
> 
> 2. Long press on that directory and select "Download Now",
> 
> 3. Wait till download is finished, then open this vault using Cryptomator.
> 
> 
> 
> I hope it helps someone else.
> 
> 
> 
> Ideally, Cryptomator app would tell iCloud to download all required files automatically.

This resolved it for me! Just tried it exactly as you shared.

**Comment by marcopallotta** [comment] 2024-01-22 17:46
@ivanRylach the problem is that in  your device you should have an amount of free space enough to store all your vault data (and it’s not always possible). Before this issue Cryotomator obviously worked also in these situations of lack of free space)
Moreover I think that  Cryptomator just downloads the file you need at real time but for some reasons it cannot do it anymore with ios17.
Again: after you download locally all the vault, what about new cloud files created from other devices? Will they suffer of the same problem (so have you to download vault every time you need new files in order to sync iCloud with local storage?)?

However thanks for your workaround.

**Comment by tobihagemann** [comment] 2024-03-15 08:20
We were finally able to reproduce it and found a fix. We'll release an update soon. Thank you all for your bug reports and patience.

Closing this as duplicate of #316.

**Closed by tobihagemann** 2024-03-15 08:20 UTC
Labels: type:duplicate
