### ISSUE TITLE
Auto clear cache on ios app or shortcut to clear cache

### ISSUE THREAD

**Issue by subbahenn** [cryptomator/ios#381] opened 2024-10-02 07:22 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Auto clear cache on ios app or shortcut to clear cache

### Motivation

I use cryptomator on Windows and iOS/iPad and nextcloud for syncing. On iOS I have to clear cache every time I want to edit again after having edited on Windows cause otherwise the file is loading with old values and directly syncs which leads to data loss. This is very annoying since I have to do this almost daily.

I‘d like to have either a possibility to auto clear cache after closing the vault (probably not possible?) or a shortcut option to clear cache so I can handle it by an automation.

### Considered Alternatives

I couldn‘t think of handling this without doing it manually.

**Comment by tobihagemann** [comment] 2024-10-10 15:09
I'd consider this a duplicate of #108.

**Closed by tobihagemann** 2024-10-10 15:09 UTC
Labels: type:duplicate
