### ISSUE TITLE
Cannot buy lifetime license on iOS

### ISSUE THREAD

**Issue by ajvenc** [cryptomator/ios#195] opened 2022-03-23 09:57 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When I make purchase via Apple Pay on my iPhone the order results in an error (picture attached to ticket). Please help resolve this issue.

### What software is involved?

- Operating System: 
- Cryptomator: 
- …

### Steps to Reproduce

Just buy the lifetime license on iPhone 13 pro max.

### Expected Behavior

To charge my card and register lifetime license under my apple id.

### Actual Behavior

Not charges my card, returns error message:

![6E53DA79-AFA9-442E-9907-0E54921988BF](https://user-images.githubusercontent.com/10097139/159672692-5c8856ed-5368-4d55-aec4-929ce3184c8d.png)

### Reproducibility

Always

**Comment by tobihagemann** [comment] 2022-03-23 10:15
Technically, a duplicate of #146. We still haven't figured out what the cause might be. Could you please send the log file, which is available in the Cryptomator settings? You can either upload them here on GitHub or send them to support@cryptomator.org, thank you!

**Comment by ajvenc** [comment] 2022-03-23 10:33
I checked the error log files (there were two of them in a zip file) and they contains the following:

_2022/03/23 09:47:46:883  Purchase of org.cryptomator.ios.iap.full_version failed with error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/03/23 09:47:46:903  Error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/03/23 09:48:43:068  Purchase of org.cryptomator.ios.iap.full_version failed with error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/03/23 09:48:43:084  Error: Error Domain=SKErrorDomain Code=0 "(null)"
_

_2022/03/23 09:44:48:337  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2022/03/23 09:46:28:019  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2022/03/23 09:47:10:273  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/1F395FD1-E12E-4FE7-BFDD-9F413C80C903/File%20Provider%20Storage/EDA7589A-10C4-4F44-A805-671BA07A1CAE/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: EDA7589A-10C4-4F44-A805-671BA07A1CAE)
2022/03/23 09:47:10:275  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/1F395FD1-E12E-4FE7-BFDD-9F413C80C903/File%20Provider%20Storage/C23C6ACF-AA67-4E33-AB00-8C987B204201/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: C23C6ACF-AA67-4E33-AB00-8C987B204201)
2022/03/23 09:48:52:097  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/1F395FD1-E12E-4FE7-BFDD-9F413C80C903/File%20Provider%20Storage/EDA7589A-10C4-4F44-A805-671BA07A1CAE/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: EDA7589A-10C4-4F44-A805-671BA07A1CAE)
2022/03/23 09:48:52:101  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/1F395FD1-E12E-4FE7-BFDD-9F413C80C903/File%20Provider%20Storage/C23C6ACF-AA67-4E33-AB00-8C987B204201/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: C23C6ACF-AA67-4E33-AB00-8C987B204201)
2022/03/23 09:50:44:246  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/1F395FD1-E12E-4FE7-BFDD-9F413C80C903/File%20Provider%20Storage/EDA7589A-10C4-4F44-A805-671BA07A1CAE/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: EDA7589A-10C4-4F44-A805-671BA07A1CAE)
2022/03/23 09:50:44:251  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/1F395FD1-E12E-4FE7-BFDD-9F413C80C903/File%20Provider%20Storage/C23C6ACF-AA67-4E33-AB00-8C987B204201/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: C23C6ACF-AA67-4E33-AB00-8C987B204201)
2022/03/23 09:51:36:994  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/1F395FD1-E12E-4FE7-BFDD-9F413C80C903/File%20Provider%20Storage/EDA7589A-10C4-4F44-A805-671BA07A1CAE/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: EDA7589A-10C4-4F44-A805-671BA07A1CAE)
2022/03/23 09:51:37:000  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/1F395FD1-E12E-4FE7-BFDD-9F413C80C903/File%20Provider%20Storage/C23C6ACF-AA67-4E33-AB00-8C987B204201/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: C23C6ACF-AA67-4E33-AB00-8C987B204201)
2022/03/23 09:59:15:098  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2022/03/23 10:26:09:931  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2022/03/23 10:26:09:937  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: 2)
_

I don't know if this helps?

**Comment by tobihagemann** [comment] 2022-03-23 10:39
Unfortunately, it's the same mysterious "unknown error": `Purchase of org.cryptomator.ios.iap.full_version failed with error: Error Domain=SKErrorDomain Code=0 "(null)"`

As far as I remember, one user reported that it helped to log out of their Apple ID and log back in. From a technical point of view, it doesn't make any sense. From the screenshots, I can see that you were able to unlock the trial. Purchasing the lifetime license is basically the same code as that, just with a different identifier.

**Closed** 2022-04-08 20:44 UTC
Labels: type:duplicate
