### ISSUE TITLE
 totally broken after update

### ISSUE THREAD

**Issue by IgiMar** [cryptomator/ios#200] opened 2022-04-06 08:20 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

After the update to ver.2.2.1 (901) vaults are not accessible anymore as a CryptomatorCommonCore.File-PriverdXPCConnctorError 4 is raised. There are no Cryptomator locations on Files anymore.

### System Setup

- iOS: 15.4.1
- Cryptomator: 2.2.1 (901)

### Cloud Type

WebDAV

### Steps to Reproduce

click on a vault

### Expected Behavior

works

### Actual Behavior

Error

### Reproducibility

Always

### Relevant Log Output

```shell
CryptomatorCommonCore.File-PriverdXPCConnctorError 4
```

**Comment by phil1995** [comment] 2022-04-06 08:35
This looks like an iOS bug, as it is impossible for us (even by mistake) to delete all locations in the Files app - because there is at least one default Cryptomator location that we cannot delete. So I would suggest to try if restarting the affected device fixes the error.

**Comment by IgiMar** [comment] 2022-04-06 08:54
Hello,
I meant that the Files app doesn't see anymore Cryptomator vaults. The
vaults still exist, obviously. Cryptomator 1 works fine.
I had restarted the iPad: same error.
Just a note: before the Cryptomator 2 update, the app worked fine. I just
opened it immediately after the update because the it claimed to have fixed
an issue I had found myself: un upload that never seemed to finish (even if
finished, as verified with Cryptomator 1).
Right after the update, I found it broken with the error I reported and the
behaviour I described.
Calling it an iOS issue seems hazardous.

All the best

Igino Marini



Il giorno mer 6 apr 2022 alle 10:35 Philipp Schmid ***@***.***>
ha scritto:

**Comment by IgiMar** [comment] 2022-04-06 09:01
P.S. The base Cryptomator location still exists. What it doesn't are the
links to the vaults that appeared in the 'locations' menù.
Hope I've been clear.

All the best

Igino Marini


Il giorno mer 6 apr 2022 alle 10:53 Igino Marini ***@***.***> ha
scritto:

**Comment by IgiMar** [comment] 2022-04-06 09:03
P.P.S.
Starting the opening process from Files, from the 'base' Location lets open
Cryptomator 2 but the error still persist while selecting Vaults.



Il giorno mer 6 apr 2022 alle 11:01 Igino Marini ***@***.***> ha
scritto:

**Comment by IgiMar** [comment] 2022-04-06 09:11
P.P.P.S
While starting the opening process from Files I'm welcomed and asked to
create a new vault in the app. Not opening the existing ones. If I click on
them, the error comes.

Il giorno mer 6 apr 2022 alle 11:03 Igino Marini ***@***.***> ha
scritto:

**Comment by IgiMar** [comment] 2022-04-06 09:23
P.P.P.P.S
I removed a Vault and re-inserted again. It works now for this vault. Not
for the others.
Hope the info you have could point you to what happened.



Il giorno mer 6 apr 2022 alle 11:11 Igino Marini ***@***.***> ha
scritto:

**Comment by phil1995** [comment] 2022-04-06 10:12
> P.S. The base Cryptomator location still exists. What it doesn't are the links to the vaults that appeared in the 'locations' menù. Hope I've been clear.

Oh okay then I misunderstood your previous message. I thought no Cryptomator location is displayed at all - which happened before the initial release, because there were "random" problems with the `bundleIdentifier`. Therefore, this should be the same issue as #176.

> P.P.P.P.S I removed a Vault and re-inserted again. It works now for this vault. Not for the others.

This is the expected behavior, since re-adding a vault triggers the registration of a new location (`NSFileProviderDomain`).

**Comment by tobihagemann** [comment] 2022-04-06 12:21
In that case, we'll mark this as a duplicate of #176. We've discussed a "blind" fix for the next update 2.2.2 since we don't know the cause of this and are unable to reproduce it.

**Closed by tobihagemann** 2022-04-06 12:21 UTC
Labels: type:bug
