### ISSUE TITLE
Unable to open Vault on Apple Vision Pro/ No UI to type password

### ISSUE THREAD

**Issue by XxBlackHatxX** [cryptomator/ios#364] opened 2024-06-22 22:13 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

The overlay to type your password doesn’t show up.

### What software is involved?

- Operating System: VisionOS 1.1, 1.2
- Cryptomator: 2.5.2
- …

### Volume Type

None

### Steps to Reproduce

1. Add a the vault using the app.
2. Open Files app and click on the vault mounts on the side bar.
3. Click unlock and nothing happens. No UI for you to type you password shows up.

### Expected Behavior

Either a UI to type in your password or the Cryptomator app should open for you to type your password within the app.

### Actual Behavior

Nothing happens so you cannot open the vault.

### Reproducibility

Always

### Anything else?

Please get the vault unlock working even if it need to be done through the app.

**Comment by tobihagemann** [comment] 2024-09-13 08:57
Duplicate of #362

**Closed by tobihagemann** 2024-09-13 08:57 UTC
Labels: type:duplicate
