### ISSUE TITLE
Auto fill issues

### ISSUE THREAD

**Issue by XxBlackHatxX** [cryptomator/ios#72] opened 2021-08-11 04:21 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When using auto fill the password UI dismisses too early.

### System Setup

- iOS: 14.7.1
- Cryptomator: 2.0.0
- …

### Steps to Reproduce

1. Open the files app and select the vault you wish to open.
2. Select the authenticate
3.  Click on the password field 
4. Select your password manager in the keyboard.

### Expected Behavior

When the password managers UI shows up Cryptomator’s UI should still stay open in the background.

### Actual Behavior

When your password manager UI is shown Cryptomator dismiss its UI before the password is able to do anything.

### Reproducibility

Always

### Relevant Log Output

```shell
N/A
```

### Anything else?

Note: that this does not happen within the Cryptomator  app itself. When I do the same thing in the app the UI stays visible after the password field is called.

The obvious workaround is to copy your password then go back into the files app and authenticate and paste the password into the password field.

**Comment by tobihagemann** [comment] 2021-08-11 06:43
Oh no... 😖 I'm not sure if we're even able to solve this because it's actually an upstream bug that we're fully aware of. We had to implement workarounds in order to get Touch ID / Face ID to work. You can still notice this bug if you cancel Touch ID / Face ID... it closes the unlock screen even though it shouldn't. It looks like that the Files app also closes the unlock screen (and with it the screen from your password manager) prematurely.

**Comment by tobihagemann** [comment] 2021-08-11 13:41
There is actually a workaround: Touch ID / Face ID is actually the reason why this is not working (as mentioned in my last comment). If you don't use Touch ID / Face ID in your password manager, it should work.

**Comment by argarner** [comment] 2021-11-01 05:02
@tobihagemann can you please confirm if the upstream bug is with iOS or the Files App itself?

**Comment by tobihagemann** [comment] 2021-11-01 08:30
I'm pretty sure that it's an issue with the Files app. I haven't noticed this behavior in other apps so I wouldn't think that it's a problem with iOS.

**Comment by tobihagemann** [comment] 2022-06-09 12:59
Quick update: We just got a notification from Apple that this upstream bug is probably fixed in iOS 16 but we haven't confirmed it yet. Fingers crossed!

**Comment by tobihagemann** [comment] 2022-09-14 21:26
Since iOS 16 has been officially released, I'll close this issue.

**Closed by tobihagemann** 2022-09-14 21:26 UTC
Labels: state:has-workaround, type:upstream-bug
