### ISSUE TITLE
Cryptomator 2 iOS search in iOS file app can't search for files

### ISSUE THREAD

**Issue by ghost** [cryptomator/ios#253] opened 2022-08-01 17:48 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

I am looking for a file in Cryptomator in the iOS Files app. The search finds nothing. Even if I am already in the exact folder of the file.

### What software is involved?

- Operating System: iOS 15.5
- Cryptomator: 2.4.1 (997)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. …

### Expected Behavior

I am searching for a file in Cryptomator in the iOS Files app and I get a search result. 

### Actual Behavior

I am searching for a file in Cryptomator in the iOS Files app and I get no search result. 

### Reproducibility

Always

**Comment by tobihagemann** [comment] 2022-08-01 18:55
Duplicate of #192

**Closed by tobihagemann** 2022-08-01 18:55 UTC
Labels: type:duplicate
