### ISSUE TITLE
Auto Logout time 

### ISSUE THREAD

**Issue by Marcusg562** [cryptomator/ios#132] opened 2021-12-21 10:46 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Cryptomator 2.0 need an auto logout switch

### Motivation

The actual versions seems not to lock the Tresor automatically. This should happen after a pre set time.

### Considered Alternatives

Lock after leaving the path

**Comment by tobihagemann** [comment] 2021-12-21 10:56
Duplicate of #64

**Closed by tobihagemann** 2021-12-21 10:56 UTC
Labels: type:duplicate
