### ISSUE TITLE
Vault version 999 shown when underlying SMB mount goes away

### ISSUE THREAD

**Issue by ericswpark** [cryptomator/ios#294] opened 2023-01-13 11:55 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Unlocking a Cryptomator vault when the underlying SMB connection has been interrupted previously results in a "vault version 999" error

### System Setup

- iOS: iOS 16.2 (20C65)
- Cryptomator: 2.4.3 (1038)

### Cloud Type

Other File Provider

### Steps to Reproduce

1. Add a vault that resides on an SMB share
2. Lock the vault
3. Quit the Cryptomator app completely
4. Unmount the SMB share
5. (Optional) remount the SMB share. (The bug happens regardless.)
6. Attempt to unlock the vault

### Expected Behavior

The vault unlocks

### Actual Behavior

The following error is shown:

"Vault version 999 is unsupported. This vault has been created with an older or newer version of Cryptomator."

![C688D2D5-9777-46A6-A6F1-A250831CED45](https://user-images.githubusercontent.com/13326074/212314534-e3a31d85-c9d4-4caf-8e79-52086f24695c.jpeg)

### Reproducibility

Always

### Relevant Log Output

```shell
2023/01/13 11:46:12:997  Unlocking vault "test" (UUIDHERE) failed with error: unsupportedVaultVersion(version: 999)
2023/01/13 11:46:50:536  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2023/01/13 11:47:11:356  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2023/01/13 11:47:18:685  Unlocking vault "test" (UUIDHERE) failed with error: unsupportedVaultVersion(version: 999)
2023/01/13 11:49:43:467  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2023/01/13 11:49:52:706  enumerateItems getAdapter failed with: defaultLock for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier
```

### Anything else?

Bug may occur with this message on previous iOS/Cryptomator versions:

"No valid file provider found with identifier 'com.apple.SMBClient-Provider.FileProvider'"

![ADC095CC-D6A9-43D3-AADB-CE53807D76E9](https://user-images.githubusercontent.com/13326074/212314760-95488a8f-5603-460d-8702-8198ca5fa663.jpeg)

See issue #262

**Comment by tobihagemann** [comment] 2023-01-20 13:41
I believe that "unmounting the SMB share" will break it irreversibly. Cryptomator uses "bookmarks" when accessing another file provider and if it's gone, it's gone. Even if you remount the SMB share, it probably won't have the same location and even if, the old bookmark becomes invalid.

I guess the error handling could be better but I don't think that there is an automated way to "recover" the vault. The only workaround is to re-add the vault.

**Comment by tobihagemann** [comment] 2023-01-25 11:05
I'm marking this as duplicate of #262, even though the error message is somewhat different but the cause is the same. It's a good way to "reproduce" it though!

**Closed by tobihagemann** 2023-01-25 11:05 UTC
Labels: type:duplicate
