### ISSUE TITLE
Cryptomator 2 Beta

### ISSUE THREAD

**Issue by Quorum75** [cryptomator/ios#49] opened 2021-07-02 11:42 UTC
It is impossible to add an existing Vault. 

For instance when trying to add Dropbox Vault I get a pop error after validing the password. 

![image](https://user-images.githubusercontent.com/49731083/124269618-6476e900-db3b-11eb-8229-b8a16082ef6e.png)

**Comment by tobihagemann** [comment] 2021-07-02 13:14
Duplicate of #43

We really don't know what could cause this but restarting the device helps for now.

**Closed by tobihagemann** 2021-07-02 13:14 UTC
Labels: type:duplicate

**Comment by Quorum75** [comment] 2021-07-04 14:54
OK it worked.
