### ISSUE TITLE
File search in iOS Files app does not work

### ISSUE THREAD

**Issue by mhsurfer** [cryptomator/ios#328] opened 2023-11-09 16:44 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

File search in iOS Files app does not work

### System Setup

- iOS: 17.1
- Cryptomator: 2.4.9
- Vault on iCloud 

### Steps to Reproduce

1. open iOS Files app and open vault 
2. put any files in any directory 
3. Search for files within Files app

### Expected Behavior

Existing files should show up.

### Actual Behavior

Search never finds anything. 

### Reproducibility

Always

**Comment by lasofeli** [comment] 2023-11-18 13:31
Seems to be duplicate of #192.

**Comment by phil1995** [comment] 2023-11-18 13:39
> Seems to be duplicate of #192.

Yes, closing this as a duplicate.

**Closed by phil1995** 2023-11-18 13:39 UTC
Labels: type:bug
