### ISSUE TITLE
Implement iOS File Provider API

### ISSUE THREAD

**Issue by andreagrandi** [cryptomator/ios#341] opened 2024-03-06 10:29 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Implement File Provider API so that other applications can access folders in Cryptomator

### Motivation

I use Cryptomator on both iOS and iPadOS and I would like to **access some of its folders from other applications** like MWeb or iA Writer.

When I try to add a folder from Cryptomator I always get an error and contacting the developers of these apps, they told me it's out of their control because it depends if the app is implementing **File Provider API** (this one https://developer.apple.com/documentation/fileprovider/ ).

For example **Working Copy** (a git client for iOS) implements it fully and I can add any folder mounted by this app, in any other app.

Do you have anthing planned on this? Or is it already implemented and should be already working?

Thanks

p.s: I'm not expert on iOS development, so I'm just passing the message here

**Comment by tobihagemann** [comment] 2024-03-06 10:34
Duplicate of #48.

Cryptomator is already using the File Provider API, but your feature request would require supporting an undocumented feature of the File Provider API. I'm aware that apps such as Working Copy seem to have a working implementation, but to our knowledge it comes with certain technical challenges.

**Closed by tobihagemann** 2024-03-06 10:34 UTC
Labels: type:duplicate

**Comment by andreagrandi** [comment] 2024-03-06 15:27
> Duplicate of #48.
> 
> Cryptomator is already using the File Provider API, but your feature request would require supporting an undocumented feature of the File Provider API. I'm aware that apps such as Working Copy seem to have a working implementation, but to our knowledge it comes with certain technical challenges.

Hi @tobihagemann and thanks for your reply. Unfortunately I'm unable to give you additional information because I'm not an iOS developer, but my understanding is that Working Copy is not the only app providing this. It seems that also Dropbox or the One client can do this (while I reckon that even pCloud doesn't allow this). I'm not sure they are using undocumented APIs because as far as I remember, the usage of undocumented API is quite risky for the App Store rules. Apps may be removed from the store if they use undocumented APIs. Could it be that since the first time you looked into this and now, Apple has released additional APIs to allow this?

I would find it a bit strange if all these apps had implemented a custom method to make their folders accessible to other apps.

From a user perspective I can tell you that this feature is quite important. I really would like to store all my documents inside a Cryptomator volume, but I need every app to be able to access them. At the moment this is not possible, so my best next option is to use iCloud as storage (which provides some sort of end to end encryption, minus meta data, I know...) since its locations are instead available from any app.

Thanks

**Comment by tobihagemann** [comment] 2024-03-07 21:16
I understand that you're not an iOS developer, but probably have a general sense as a software engineer. Please read https://github.com/owncloud/ios-app/issues/604, then you'll probably understand this issue better.

But you're right... this is all very strange. I have the feeling that Apple doesn't have that much of a focus on the File Provider API. (This is not the only example that we struggled with... the API is full of weird bugs and feels incomplete.)

I don't believe that anything has changed in these years. `NSExtensionFileProviderSupportsPickingFolders` is still undocumented. But using it shouldn't be "risky" in regard to rejection, because it's not private API. It's just undocumented.

The only thing that's "new" is the introduction of [`NSFileProviderReplicatedExtension`](https://developer.apple.com/documentation/fileprovider/nsfileproviderreplicatedextension) with iOS 16. I don't know if rewriting everything to it would change anything in that regard. But that would be absolute madness.
