### ISSUE TITLE
the deletion of configuration files is not considered by the IOS application

### ISSUE THREAD

**Issue by nassim-2000** [cryptomator/ios#143] opened 2021-12-30 12:54 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Issue deleted without response. M y problem is that when I delete the masterkey.cryptomator and vault.cryptomator files, I still manage to unlock the vault. Files are not considered.

### What software is involved?

- Operating System: IOS 15.1.1
- Cryptomator: 2.0.4 (mobile app)

### Volume Type

FUSE

### Steps to Reproduce

1. [First Step]
Create a vault
2. [Second Step]
Delete the files configuration
3. …
The decrypting is successfully without the files configuration

### Expected Behavior

An error wich explain who files configuration are not found

### Actual Behavior

The decrypting is successfully without masterkey

### Reproducibility

Always

**Comment by tobihagemann** [comment] 2021-12-30 13:20
Duplicate of #142

**Comment by tobihagemann** [comment] 2021-12-30 13:21
I didn't delete your issue, I transferred it to the correct repository, see #142.

**Closed by tobihagemann** 2021-12-30 13:20 UTC
Labels: type:duplicate

**Comment by nassim-2000** [comment] 2021-12-30 16:05
ah I'm sorry to have judged too quickly
thanks
