### ISSUE TITLE
Cannot save file until locking/unlocking

### ISSUE THREAD

**Issue by USER19464727** [cryptomator/ios#183] opened 2022-03-02 14:19 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Cannot save files until locking/unlocking

### What software is involved?

- Operating System: iOS 15.3.1
- Cryptomator: 2.1.2 (838)

### Steps to Reproduce

1. Try to save a file or Scan Document into a folder within an open vault

### Expected Behavior

I expect that the file properly saves

### Actual Behavior

I either get an error that the file cannot be found or cannot be copied or something. If using Scan Documents, it completes the scan and there is no error. The file simply is not saved. If I lock the vault, unlock the vault, and attempt the same action it succeeds.

### Reproducibility

Intermittent

**Comment by USER19464727** [comment] 2022-03-02 15:37
iCloud Drive

**Comment by tobihagemann** [comment] 2022-03-03 09:21
I'm pretty sure now that this is a duplicate of #179 (and #181). Closing this and we'll continue the discussion in #179.

**Closed by tobihagemann** 2022-03-03 09:21 UTC
Labels: type:duplicate
