### ISSUE TITLE
Add auto upload for pictures.

### ISSUE THREAD

**Issue by ph00lt0** [cryptomator/ios#208] opened 2022-04-14 17:23 UTC
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Add auto upload feature for pictures taken to cryptomator webdav

### Motivation

I want to replace faulty nextcloud with cryptomator and etasync. Are there any plans for integrating auto upload of pictures? It would make our life significantly better!

### Considered Alternatives

Uploading manually isn't the best and also requires manual deletion. 

### Anything else?

Implement this like nextcloud but then good :)

**Comment by tobihagemann** [comment] 2022-04-14 18:03
Duplicate of #114

**Closed by tobihagemann** 2022-04-14 18:03 UTC
Labels: type:duplicate
